# Generated by Django 4.0.4 on 2022-06-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('skills', models.JSONField()),
                ('github_available', models.BooleanField(default=True)),
                ('project_url', models.CharField(max_length=120)),
                ('github_url', models.CharField(max_length=120)),
            ],
        ),
    ]
